baseurl = "/"
languageCode = "en-us"
title = "mlesniak.com"
theme = "hugo-classic"
googleAnalytics = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
    name = "mlesniak.com"
    url = "/"
    weight = 1
#[[menu.main]]
#    name = "Categories"
#    url = "/categories/"
#    weight = 2
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.feed]]
    name = "Contact"
    url = "/post/1/01/01/contact/index.html"
    weight = 4
[[menu.feed]]
    name = "Feed"
    url = "/index.xml"
    weight = 5

[params]
    description = "My blog about my life."
    footer = "Open-Source | [Github](https://github.com/goodroot/hugo-classic) | [Twitter](https://twitter.com/thegoodroot)"
    #custom_css = ["css/theme-override.css"]
