# Basic config
baseURL = "https://example.com"
theme = "hugo-simple"
languageCode = "en"
title = "Dr. Michael Lesniak -- Freelancer | Software Engineer | Software Architect"
copyright = "© 2024 Dr. Michael Lesniak"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
# ignoreErrors = ["error-disable-taxonomy"]
[taxonomies]
tag = "tags"

[permalinks]
blog = "/:slugorfilename/"
tags = "/blog/:slug"

[markup]
defaultMarkdownHandler = 'goldmark'
[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.renderer]
unsafe = true
[markup.tableOfContents]
startLevel = 2
endLevel = 3
[markup.highlight]
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "catppuccin-mocha"

[params]
description = "Homepage of Dr. Michael Lesniak (Freelancer, Software Engineer, Software Architect)"
favicon = "images/favicon.png"
dateFormat = "2006-01-02"
hideMadeWithLine = true
[params.author]
name = "Dr. Michael Lesniak"
email = "mail@mlesniak.com"

[[menu.main]]
name = "Home"
pageRef = "/"
weight = 10
[[menu.main]]
name = "Resume"
pageRef = "/resume"
weight = 20
[[menu.main]]
name = "Contact & Legal Notice"
url = "/contact"
weight = 30

#[services.rss]
#limit = 42

#[outputs]
# Disable section RSS
#section = ["html"]
